source:      _source
destination: _deploy
timezone:	America/New_York
webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"